export const PERMISSIONS = {
  DASHBOARD: {
    READ_DASHBOARD: "READ DASHBOARD",
    READ_DASHBOARD_ANALYTIC: "READ DASHBOARD ANALYTIC",
  },
  USERS: {
    READ_USERS: "READ USERS",
    CREATE_USERS: "CREATE USERS",
    UPDATE_USERS: "UPDATE USERS",
    DELETE_USERS: "DELETE USERS",
  },
};
